volumes:
  opensearch-data:

services:
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    volumes:
      - opensearch-data:/usr/share/opensearch/data
   

  embedding:
    build: ./embedding_advance
    volumes:
      - ./pdf_corpus:/app/pdf_corpus
    environment:
      - OPENSEARCH_ENDPOINT=http://opensearch:9200
    depends_on:
      - opensearch
  
  api:
    build: ./api_advance
    environment:
      OPENSEARCH_ENDPOINT: http://opensearch:9200
    depends_on:
      - opensearch


  app:
    build: ./app_advance
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_URL=http://113.53.253.56:11434
    depends_on:
      - api

  
