2025.03.24 วันจันทร์
00:14 kong Amornpan pandoc 01-หลักการและเหตุผล.md 02-วัตถุประสงค์.md 03-ประโยชน์ที่ได้รับ.md 04-คุณสมบัติของผู้เสนอราคา.md 05-ขอบเขตของงาน.md 06-การจ้างงานที่ผลิตในประเทศ.md 07-หลักเกณฑ์การพิจารณา.md 08-งบประมาณ.md 09-ราคากลาง.md 10-การรับประกันผลงาน.md 11-ข้อกำหนดการเสนอราคา.md 12-ระยะเวลาดำเนินงาน.md 13-การเบิกจ่ายค่าตอบแทน.md 14-ค่าปรับ.md 15-สิทธิในทรัพย์สินทางปัญญา.md 16-การรักษาความลับของผู้รับจ้าง.md 17-การดำเนินการตามพระราชบัญญัติคุ้มครองข้อมูลส่วนบุคคล.md 18-ผู้รับผิดชอบโครงการ.md 19-กรรมการTOR.md -s -o combined.docx

09:11 kong Amornpan SENT-2025-NT-Understanding LLM   and Implementing RAG.pdf
09:47 kong Amornpan ช่วยให้สามารถเชื่อมต่อและจัดการข้อมูลจากหลายแหล่ง, สร้างฐานความรู้ (knowledge base), และใช้เทคนิคเช่น RAG (Retrieval-Augmented Generation) เพื่อดึงข้อมูลที่เกี่ยวข้องไปใช้งานร่วมกับโมเดล AI เช่น GPT เพื่อให้ได้คำตอบที่แม่นยำและตรงกับข้อมูลเฉพาะของผู้ใช้มากขึ้น
09:53 kong Amornpan เชื่อมต่อและประมวลผลข้อมูลองค์กรที่ซับซ้อนและหลากหลายรูปแบบ เช่น PDF, PowerPoint, Excel, ฐานข้อมูล, และแหล่งข้อมูลบนคลาวด์.
•
สร้างดัชนีความรู้ (Index) จากข้อมูลที่ไม่มีโครงสร้าง.
•
ช่วยในการค้นหาข้อมูล (Find information) และ สังเคราะห์ข้อมูลเชิงลึก (Synthesize insights) จากข้อมูล.
รองรับการสร้างระบบ RAG (Retrieval-Augmented Generation) เพื่อเพิ่มประสิทธิภาพของ Large Language Models ในการดึงข้อมูลที่เกี่ยวข้อง.
•
มีเครื่องมือสำหรับแยกวิเคราะห์เอกสารที่ซับซ้อน (Parse complex documents) เช่น ตารางและโครงสร้างแบบลำดับชั้น.
•
จัดการการตั้งค่า การวนซ้ำ และการปรับแต่ง RAG (Handle RAG set up, iteration, and tuning).
มีเฟรมเวิร์กสำหรับสร้าง Agentic Workflows ที่เอเจนต์ AI สามารถทำงานร่วมกันได้.
•
มีระบบนิเวศที่กว้างขวางของตัวเชื่อมต่อ (Connectors) สำหรับแหล่งข้อมูล, vector stores, และ LLMs ต่างๆ.
•
ช่วยในการสร้างและปรับใช้ (Build and deploy) Knowledge Assistants และแอปพลิเคชัน AI.
13:56 kong Amornpan รูป
13:58 kong Amornpan รูป
14:00 kong Amornpan รูป
14:01 kong Amornpan รูป
14:01 kong Amornpan รูป
14:02 kong Amornpan รูป
14:03 kong Amornpan รูป
14:22 kong Amornpan รูป
2025.03.25 วันอังคาร
09:31 kong Amornpan รูป
09:41 kong Amornpan import pandas as pd

# Data as a list of dictionaries
data = [
    {"รายการ": "1. หมวดค่าตอบแทน", "เดือนละ": "", "งวดที่ 1": 1080000, "งวดที่ 2": 900000, "งวดที่ 3": 180000, "รวม": 2160000},
    {"รายการ": "1.1 หัวหน้าโครงการวิจัย อมรพันธ์ พรชัยเจริญ", "เดือนละ": 80000, "งวดที่ 1": 480000, "งวดที่ 2": 400000, "งวดที่ 3": 80000, "รวม": 960000},
    {"รายการ": "1.2 นักวิจัย", "เดือนละ": 50000, "งวดที่ 1": 300000, "งวดที่ 2": 250000, "งวดที่ 3": 50000, "รวม": 600000},
    {"รายการ": "1.3 นักวิจัย", "เดือนละ": 50000, "งวดที่ 1": 300000, "งวดที่ 2": 250000, "งวดที่ 3": 50000, "รวม": 600000},
    {"รายการ": "2. หมวดค่าจ้าง", "เดือนละ": "", "งวดที่ 1": 240000, "งวดที่ 2": 240000, "งวดที่ 3": 0, "รวม": 480000},
    {"รายการ": "2.1 ผู้ช่วยนักวิจัย", "เดือนละ": 40000, "งวดที่ 1": 240000, "งวดที่ 2": 240000, "งวดที่ 3": 0, "รวม": 480000},
    {"รายการ": "3. หมวดค่าใช้สอย", "เดือนละ": "", "งวดที่ 1": 2219000, "งวดที่ 2": 1250000, "งวดที่ 3": 640000, "รวม": 3109000},
    {"รายการ": "3.1 ค่าพัฒนาระบบและแพลตฟอร์ม", "เดือนละ": "", "งวดที่ 1": 900000, "งวดที่ 2": 380000, "งวดที่ 3": 120000, "รวม": 1400000},
    {"รายการ": "3.2 ค่าจัดประชุมและฝึกอบรม", "เดือนละ": "", "งวดที่ 1": 40000, "งวดที่ 2": 50000, "งวดที่ 3": 30000, "รวม": 120000},
    {"รายการ": "3.3 ค่าบำรุงรักษาระบบและบริการวิชาการ", "เดือนละ": "", "งวดที่ 1": 0, "งวดที่ 2": 150000, "งวดที่ 3": 110000, "รวม": 260000},
    {"รายการ": "3.4 ค่าใช้จ่ายในการเดินทางและดำเนินงาน", "เดือนละ": "", "งวดที่ 1": 100000, "งวดที่ 2": 100000, "งวดที่ 3": 30000, "รวม": 230000},
    {"รายการ": "3.5 ค่าเช่าบริการคลาวด์และระบบคอมพิวเตอร์", "เดือนละ": "", "งวดที่ 1": 600000, "งวดที่ 2": 400000, "งวดที่ 3": 200000, "รวม": 1200000},
    {"รายการ": "3.6 ค่าจัดทำรายงานผลการวิจัยโดยผู้เชี่ยวชาญ", "เดือนละ": "", "งวดที่ 1": 0, "งวดที่ 2": 50000, "งวดที่ 3": 50000, "รวม": 100000},
    {"รายการ": "3.7 ค่าบริการวิเคราะห์และประมวลผลข้อมูลพิเศษ", "เดือนละ": "", "งวดที่ 1": 0, "งวดที่ 2": 50000, "งวดที่ 3": 40000, "รวม": 90000},
    {"รายการ": "3.8 ค่าประเมินและรับรองคุณภาพระบบ", "เดือนละ": "", "งวดที่ 1": 0, "งวดที่ 2": 0, "งวดที่ 3": 60000, "รวม": 60000},
    {"รายการ": "3.9 ค่าจ้างเหมาบริการทำเอกสาร", "เดือนละ": "", "งวดที่ 1": 9000, "งวดที่ 2": 20000, "งวดที่ 3": 0, "รวม": 29000},
    {"รายการ": "3.10 ค่าจัดประชุมเพื่อนำเสนอความก้าวหน้าโครงการ", "เดือนละ": "", "งวดที่ 1": 60000, "งวดที่ 2": 50000, "งวดที่ 3": 0, "รวม": 110000},
    {"รายการ": "4. ค่าวัสดุ", "เดือนละ": "", "งวดที่ 1": 20000, "งวดที่ 2": 20000, "งวดที่ 3": 10000, "รวม": 50000},
    {"รายการ": "4.1 ค่าวัสดุสำนักงาน", "เดือนละ": "", "งวดที่ 1": 20000, "งวดที่ 2": 20000, "งวดที่ 3": 10000, "รวม": 50000},
    {"รายการ": "5. ค่าธรรมเนียมสถาบัน", "เดือนละ": "", "งวดที่ 1": 0, "งวดที่ 2": 0, "งวดที่ 3": 201000, "รวม": 201000},
    {"รายการ": "รวมงบประมาณทั้งหมด", "เดือนละ": "", "งวดที่ 1": 3559000, "งวดที่ 2": 2410000, "งวดที่ 3": 1031000, "รวม": 6000000},
]

# Create DataFrame
df = pd.DataFrame(data)

# Save to Excel
excel_path = '/mnt/data/budget_plan.xlsx'
df.to_excel(excel_path, index=False)

excel_path

10:03 kong Amornpan แบบฟอร์มแตกตัวคูณ ORG.xlsx
11:58 kong Amornpan ที่พี่บอกว่าจะโอนย้ายทรัพย์สินมาเป็นของ นธย.
12:00 kong Amornpan แล้วที่บอกให้ผมไปเชิญชวนให้คนมาทำวิจัยที่เราแบบนี้จะยังไงหรอคับ
13:27 kong Amornpan demo งาน Agentic RAG ครับผม
20:48 kong Amornpan A4_สำเนาบัตรประชาชน_ก้อง_บีน.pdf
21:31 kong Amornpan Note 9 Oct BE 2566 (2).pdf
21:31 kong Amornpan Note 9 Oct BE 2566 (2).pdf
21:41 kong Amornpan A4_สำเนาบัตรประชาชน_ก้อง_บีน.pdf
2025.03.26 วันพุธ
09:21 kong Amornpan รูป
09:46 kong Amornpan บันทึก 10 ต.ค. 2567.pdf
11:26 kong Amornpan # 1. หยุดการทำงานของ Ollama
sudo snap stop ollama

# 2. ถอนการติดตั้ง Snap package
sudo snap remove ollama

# 3. ติดตั้งใหม่ผ่าน script ทางการ
curl -fsSL https://ollama.com/install.sh | sh

# 4. สร้าง systemd service ที่ตั้งค่า OLLAMA_HOST
sudo bash -c 'cat > /etc/systemd/system/ollama.service << EOF
[Unit]
Description=Ollama Service
After=network.target

[Service]
Environment="OLLAMA_HOST=0.0.0.0:11434"
ExecStart=/usr/local/bin/ollama serve
User='$(whoami)'
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF'

# 5. เปิดใช้งานและเริ่มต้น service
sudo systemctl daemon-reload
sudo systemctl enable ollama
sudo systemctl start ollama

# 6. ตรวจสอบสถานะ service
sudo systemctl status ollama

# 7. ตรวจสอบว่า Ollama กำลังฟังที่ 0.0.0.0
sudo netstat -tulpn | grep 11434

# 8. เปิด firewall port 11434 (ถ้าใช้งาน ufw)
sudo ufw allow 1143
14:53 kong Amornpan รูป
15:10 kong Amornpan รูป
16:50 kong Amornpan OPENSEARCH_ENDPOINT = "http://34.41.37.53:9200"
16:52 kong Amornpan OLLAMA_API_ENDPOINT = "http://113.53.253.56:11434/api/generate"
19:07 kong Amornpan # อัปเดตระบบ
sudo apt update
sudo apt upgrade -y

# ติดตั้ง dependencies ที่จำเป็น
sudo apt install -y apt-transport-https ca-certificates curl software-properties-common gnupg

# เพิ่ม Docker GPG key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

# เพิ่ม Docker repository
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# อัปเดต apt อีกครั้งและติดตั้ง Docker
sudo apt update
sudo apt install -y docker-ce docker-ce-cli containerd.io

# ติดตั้ง Docker Compose
sudo apt install -y docker-compose

# เพิ่มผู้ใช้ปัจจุบันเข้ากลุ่ม docker (เพื่อให้รัน docker ได้โดยไม่ต้องใช้ sudo)
sudo usermod -aG docker $USER

# เริ่มการทำงานและตั้งค่าให้ Docker ทำงานเมื่อบูต
sudo systemctl start docker
sudo systemctl enable docker

# ตรวจสอบว่า Docker ติดตั้งสำเร็จ
docker --version
docker-compose --version
2025.03.27 วันพฤหัสบดี
06:42 kong Amornpan https://aekanunbigdata.medium.com/%E0%B8%AA%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%87-rag-%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B9%80%E0%B8%81%E0%B9%88%E0%B8%87%E0%B8%81%E0%B8%A7%E0%B9%88%E0%B8%B2%E0%B9%80%E0%B8%94%E0%B8%B4%E0%B8%A1-%E0%B8%95%E0%B8%B4%E0%B8%94%E0%B8%95%E0%B8%B1%E0%B9%89%E0%B8%87%E0%B8%9A%E0%B8%99-windows-%E0%B9%83%E0%B8%99-5-%E0%B8%82%E0%B8%B1%E0%B9%89%E0%B8%99%E0%B8%95%E0%B8%AD%E0%B8%99-%E0%B8%97%E0%B8%B3%E0%B8%87%E0%B8%B2%E0%B8%99%E0%B8%9A%E0%B8%99-local-%E0%B8%A3%E0%B8%AD%E0%B8%87%E0%B8%A3%E0%B8%B1%E0%B8%9A-agentic-2ed91d86886a
15:46 kong Amornpan app.zip
15:51 kong Amornpan volumes:
  opensearch-data:

services:
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    volumes:
      - opensearch-data:/usr/share/opensearch/data
   

  embedding:
    build: ./embedding_advance
    volumes:
      - ./pdf_corpus:/app/pdf_corpus
    environment:
      - OPENSEARCH_ENDPOINT=http://opensearch:9200
    depends_on:
      - opensearch
  
  api:
    build: ./api_advance
    environment:
      OPENSEARCH_ENDPOINT: http://opensearch:9200
    depends_on:
      - opensearch


  app:
    build: ./app_advance
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_URL=http://113.53.253.56:11434
    depends_on:
      - api

  
